### PR TITLE
Add RQGIS data to spDataLarge

### PR DESCRIPTION
**Pull request by jannes-m**
Hey Jakub,
in accordance with Robin's suggestion I would like to move the data from **RQGIS(3)** to **spDataLarge**. If there is still anything to do regarding the data, please let me know (e.g., the wgs84 ellps warning message keeps popping up but I am not sure if there is anything we can do about it atm).
All the best and hear you soon!
Jannes

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Great to see this, not tested but looks good to me! Look good to you @Nowosad ?

**Comment by Nowosad** [comment]
Thanks @jannes-m @Robinlovelace - I will look at it carefully later this week.

**Comment by Robinlovelace** [comment]
One question for @jannes-m could the smaller datasets (grain?) move to `spData`? That could help future development work if there's space.

**Comment by jannes-m** [comment]
sure these datasets (grain, elevation, etc) could go into spData, but @Nowosad wanted me to put them into spDataLarge back then, not sure why, do you remember @Nowosad ?

**Comment by Robinlovelace** [comment]
I think the reason is to keep `spData` small and simple. If the datasets are small and simple I see no downside but if there are larger datasets (e.g. bigger than 100 kB) they may be worth putting in the `spDataLarge` repo. Just my thoughts.

**Comment by Nowosad** [comment]
@Robinlovelace I would keep these datasets (grain, elevation, etc) in **spDataLarge** as they are mostly (only?) used in our book. Most of the datasets in **spData** are used not only in our book, but also in other packages documentation, etc.

**Comment by Nowosad** [comment]
Thanks @jannes-m !

**Comment by Robinlovelace** [comment]
> @Robinlovelace I would keep these datasets (grain, elevation, etc) in spDataLarge as they are mostly (only?) used in our book. Most of the datasets in spData are used not only in our book, but also in other packages documentation, etc.

Reasonable, makes sense.

**Pull request merged**
